version: '3.8'

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    networks:
      - mynetwork
    container_name: db-1
    hostname: localhost
  app23:
    depends_on:
      - db
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge